@extends('layouts.app')
@section('content')

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;600;700&display=swap" />
    <link rel="stylesheet" href="index.css" />
    @vite(['resources/css/regestar.css'])


  </head>
  <body>
    <div class="main-container">
      <div class="box">
        <div class="wrapper"><span class="text">الإسم الرباعي:</span></div>
        <div class="section"></div>
      </div>
      <div class="wrapper-2">
        <div class="wrapper-3">
          <div class="box-2">
            <span class="text-2"
              >اوافق على سياسة الشروط والاحكام والخصوصية</span
            >
            <div class="pic"></div>
          </div>
          <span class="text-3"
            >يجب قراءة سياسة الشروط والاحكام والخصوصية قبل التسجيل</span
          >
        </div>
        <div class="group">
          <div class="wrapper-4">
            <span class="text-4">التسجيل عن طريق جوجل</span>
            <div class="pic-2"></div>
          </div>
        </div>
        <div class="group-2"></div>
        <span class="text-5">إنشاء الحساب</span>
      </div>
      <div class="group-3"></div>
      <div class="img"></div>
      <div class="box-3">
        <span class="text-6">مرحباً بك في ألفا</span
        ><span class="text-7"
          >أنشئ حسابك وتابع دروسك بشكل إلكترونيّ وبجودة عالية</span
        >
      </div>
      <div class="group-4">
        <div class="wrapper-5"></div>
        <div class="section-2"><span class="text-8">الفرع:</span></div>
        <div class="group-5">
          <span class="text-9">صناعي</span>
          <div class="wrapper-6"></div>
        </div>
        <div class="box-4">
          <span class="text-a">ادبي</span>
          <div class="box-5"></div>
        </div>
        <div class="wrapper-7">
          <span class="text-b">علمي</span>
          <div class="group-6"></div>
        </div>
      </div>
      <div class="section-3">
        <div class="group-7"><span class="text-c">المحافظة:</span></div>
        <div class="group-8"></div>
      </div>
      <div class="wrapper-8">
        <div class="group-9"><span class="text-d">رقم الهاتف:</span></div>
        <div class="group-a"></div>
      </div>
      <div class="section-4">
        <div class="box-6"><span class="text-e">الإيميل:</span></div>
        <div class="wrapper-9"></div>
      </div>
      <div class="section-5">
        <div class="wrapper-a">
          <span class="text-f">تأكيد كلمة المرور:</span>
        </div>
        <div class="group-b"></div>
      </div>
      <div class="wrapper-b">
        <div class="box-7"><span class="text-10">كلمة المرور:</span></div>
        <div class="section-6"></div>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>

@endsection